name: Process and update data

on:
  push:
    paths:
      - "public/dataset.json"

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Process Dataset
        run: npm run process-data

      - name: Predeploy
        run: CI=false npm run predeploy

      - name: Install git
        run: sudo apt-get install git

      - name: Configure git
        run: git config user.name github-actions && git config user.email git config user.email github-actions@github.com

      - name: Deploy
        run: CI=false npm run deploy
